//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Контроль_и_Учет_v1._2.DB_ModelContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_DocumentsEntities : DbContext
    {
        public DB_DocumentsEntities()
            : base("name=DB_DocumentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<addressTypes> addressTypes { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Directors> Directors { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<DocumentTitle> DocumentTitle { get; set; }
        public virtual DbSet<Firms> Firms { get; set; }
        public virtual DbSet<Providers> Providers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
