//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Контроль_и_Учет_v1._2.DB_ModelContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Providers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Providers()
        {
            this.Firms = new HashSet<Firms>();
            this.Contracts = new HashSet<Contracts>();
        }
    
        public int IdProvider { get; set; }
        public string TitleProvider { get; set; }
        public Nullable<int> IdAddressProviderLegal { get; set; }
        public Nullable<int> IdAddressProviderActual { get; set; }
        public Nullable<int> IdDirector { get; set; }
        public Nullable<int> IdAddressStore { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        public virtual Addresses Addresses1 { get; set; }
        public virtual Addresses Addresses2 { get; set; }
        public virtual Directors Directors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Firms> Firms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }
    }
}
